name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm i -D
    - run: npm run build
    - name: Commit report
      run: |
        git config --global user.name 'hypothete'
        git config --global user.email 'hypothete@users.noreply.github.com'
        git commit -am "Updated dependencies"
        git push
      env:
        CI: true